version: '3'

networks:
  vps-traefik:
    name: proxynet
    external: true

services:
  whoami:
    # A container that exposes an API to show its IP address
    image: "containous/whoami"
    container_name: "whoami"
    restart: "unless-stopped"
    networks:
      - vps-traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.pablomalo.fr`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.port=8900"
