version: '3'

networks:
  proxynet:
    external: true

services:
  whoami:
    image: 'containous/whoami'
    container_name: whoami
    restart: 'unless-stopped'
    networks:
      - proxynet
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.whoami.rule=Host(`${HOSTNAME}`)'
      - 'traefik.http.routers.whoami.entryPoints=websecure'
      - 'traefik.http.routers.whoami.tls=true'
      - 'traefik.http.middlewares.sslHeader.headers.customrequestheaders.X-Forwarded-Proto=https'
